blog post for argus
moldedbits/moldedbits.github.io pull request #39
Opened 2017-06-26 10:35 UTC by abhishekBansal

2017-06-28 12:59 UTC, anujmiddha commented
@aksswami please review and merge

2017-06-29 04:03 UTC, aksswami requested changes

2017-06-29 04:03 UTC, aksswami commented on _posts/2017-06-26-introducing-argus.md
> +At [moldedbits](http:///www.moldedbits.com), we do a lot of client projects. Be it an enterprise app, a social networking app or an app for a small business, most all apps need a user on-boarding flo
most all apps?

2017-06-29 04:03 UTC, aksswami commented on _posts/2017-06-26-introducing-argus.md
> +Argus is fully customizable and it adapts look and feel of your application. Its open source and free to use.
We can remove *It's open source and free to use. As we already have license in place for this

2017-06-29 05:02 UTC, aksswami approved these changes

2017-06-29 05:02 UTC, aksswami commented on _posts/2017-06-26-introducing-argus.md
> +Argus is fully customizable and it adapts look and feel of your application. Its open source and free to use.
should remove.

2017-06-29 05:39 UTC, merged